### ISSUE TITLE
BE: 상품 및 상품 거래량 관련 엔티티 설계 진행

### ISSUE THREAD

**Issue by sojeongLee0125** [codestates-seb/seb41_main_008#7]
# 현재 진행 중인 작업

상품, 상품 컬렉션, 거래 정보, 카트 정보, 엔티티 설계 및 연관관계 매핑 진행중

# 추가적으로 할 말.
첫번째 웹 훅 테스트!!!!

**Comment by jaehak24** [comment]
oauth2.0
> 관련 사전 프로젝트 실습 진행
추가적으로 할 말 
> none

**Comment by jaehak24** [comment]
수고하셨습니다! bb
